# Generated by Django 5.0.2 on 2024-10-27 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100, null=True)),
                ('data_contratacao', models.DateField()),
                ('imagem', models.ImageField(upload_to='media/')),
                ('hub', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontualidade', models.IntegerField()),
                ('organizacao', models.IntegerField()),
                ('comunicacao', models.IntegerField()),
                ('resolucao_problemas', models.IntegerField()),
                ('precisao', models.IntegerField()),
                ('velocidade', models.IntegerField()),
                ('conhecimento_ferramentas', models.IntegerField()),
                ('flexibilidade', models.IntegerField()),
                ('postura_profissional', models.IntegerField()),
                ('priorizacao_tarefas', models.IntegerField()),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='avaliacao.colaborador')),
            ],
        ),
    ]
