# Generated by Django 5.0.2 on 2024-11-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='avaliador',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='loja',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
