# Generated by Django 5.0.2 on 2024-11-20 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avaliacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(choices=[('Líder de Logística', 'Líder de Logística'), ('Assistente de Logística', 'Assistente de Logística'), ('Mensageiro', 'Mensageiro'), ('Supervisor', 'Supervisor'), ('Staf', 'Staf')], max_length=100, null=True)),
                ('data_contratacao', models.DateField()),
                ('imagem', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliador', models.CharField(max_length=255)),
                ('loja', models.CharField(max_length=255)),
                ('pontualidade', models.IntegerField()),
                ('organizacao', models.IntegerField()),
                ('comunicacao', models.IntegerField()),
                ('resolucao_problemas', models.IntegerField()),
                ('precisao', models.IntegerField()),
                ('velocidade', models.IntegerField()),
                ('conhecimento_ferramentas', models.IntegerField()),
                ('flexibilidade', models.IntegerField()),
                ('postura_profissional', models.IntegerField()),
                ('priorizacao_tarefas', models.IntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('data', models.DateField(auto_now_add=True)),
                ('nota', models.FloatField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='avaliacao.colaborador')),
            ],
        ),
        migrations.AddField(
            model_name='colaborador',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='avaliacao.hub'),
        ),
    ]
