# Generated by Django 5.0.2 on 2024-11-20 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medalha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medalhas', to='avaliacao.colaborador')),
            ],
            options={
                'verbose_name': 'Medalha',
                'verbose_name_plural': 'Medalhas',
            },
        ),
    ]
