# Generated by Django 5.0.2 on 2024-11-11 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0002_alter_avaliacao_avaliador_alter_avaliacao_loja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='avaliador',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='loja',
            field=models.CharField(max_length=255),
        ),
    ]
