# Generated by Django 5.0.2 on 2025-02-12 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0003_medalha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaborador',
            options={'verbose_name': 'Colaborador', 'verbose_name_plural': 'Colaboradores'},
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='data_contratacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Avaliacao_Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliador', models.CharField(max_length=255)),
                ('loja', models.CharField(max_length=255)),
                ('rapidez_atendimento', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('eficiencia_resolucao', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('clareza_comunicacao', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('profissionalismo', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('suporte_gestao_pedidos', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('proatividade', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('disponibilidade', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('satisfacao_geral', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('data', models.DateField(auto_now_add=True)),
                ('nota', models.FloatField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_restaurantes', to='avaliacao.colaborador')),
            ],
        ),
    ]
