# Generated by Django 5.0.2 on 2024-11-12 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0003_alter_avaliacao_avaliador_alter_avaliacao_loja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='avaliacao.loja'),
        ),
        migrations.AddField(
            model_name='loja',
            name='shopping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lojas', to='avaliacao.shopping'),
        ),
    ]
