# Generated by Django 5.0.2 on 2024-10-31 21:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0003_avaliacao_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='cargo',
            field=models.CharField(choices=[('Líder de Logística', 'Líder de Logística'), ('Assistente de Logística', 'Assistente de Logística'), ('Mensageiro', 'Mensageiro'), ('Supervisor', 'Supervisor'), ('Staf', 'Staf')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='hub',
            field=models.CharField(blank=True, choices=[('Shopping Boulevard', 'Shopping Boulevard'), ('Aurora Shopping', 'Aurora Shopping')], max_length=255, null=True),
        ),
    ]
