# Generated by Django 5.0.2 on 2024-10-31 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0004_avaliacao_data_alter_colaborador_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='nota',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
