# Generated by Django 5.0.2 on 2025-03-02 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0004_alter_colaborador_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='avaliacao_restaurante',
            name='clareza_comunicacao',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='avaliacao_restaurante',
            name='disponibilidade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='avaliacao_restaurante',
            name='eficiencia_resolucao',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='avaliacao_restaurante',
            name='proatividade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='avaliacao_restaurante',
            name='profissionalismo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='avaliacao_restaurante',
            name='rapidez_atendimento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='avaliacao_restaurante',
            name='satisfacao_geral',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='avaliacao_restaurante',
            name='suporte_gestao_pedidos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='avaliacao_restaurante',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_restaurantes', to='avaliacao.loja'),
        ),
    ]
