# Generated by Django 5.0.2 on 2024-11-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0005_alter_avaliacao_loja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loja',
            name='shopping',
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='loja',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Shopping',
        ),
        migrations.DeleteModel(
            name='Loja',
        ),
    ]
