# Generated by Django 5.0.2 on 2025-03-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0005_loja_alter_avaliacao_restaurante_clareza_comunicacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao_restaurante',
            name='loja',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Loja',
        ),
    ]
