# Generated by Django 5.0.2 on 2025-03-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0006_alter_avaliacao_restaurante_loja_delete_loja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medalha',
            name='quantidade',
        ),
        migrations.AlterField(
            model_name='medalha',
            name='tipo',
            field=models.CharField(blank=True, choices=[('1_ano', '1 Ano de Hub'), ('2_anos', '2 Anos de Hub'), ('3_anos', '3 Anos de Hub'), ('logistica', 'Logística Implacável'), ('mensageiro', '1# Mensageiro'), ('pontual', 'Super Pontual'), ('criatividade', 'Criatividade'), ('destaque', 'Colaborador Destaque'), ('comunicação', 'Comunicação Eficiente'), ('carisma', 'Carisma'), ('dedicação', 'Dedicação'), ('analista', 'Analista de Dados')], max_length=50, null=True),
        ),
    ]
