# Generated by Django 5.0.2 on 2024-11-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0007_hub_alter_colaborador_hub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='comunicacao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='conhecimento_ferramentas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='flexibilidade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='organizacao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pontualidade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='postura_profissional',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='precisao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='priorizacao_tarefas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='resolucao_problemas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='velocidade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
