# Generated by Django 5.0.2 on 2025-11-10 21:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0007_remove_medalha_quantidade_alter_medalha_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao_restaurante',
            name='colaborador',
        ),
        migrations.CreateModel(
            name='AvaliacaoAssistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliador', models.CharField(max_length=255)),
                ('data_avaliacao', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Avaliação')),
                ('proatividade', models.PositiveSmallIntegerField(choices=[(1, '1 - Muito Abaixo'), (2, '2 - Abaixo do Esperado'), (3, '3 - Esperado'), (4, '4 - Acima do Esperado'), (5, '5 - Excepcional')])),
                ('responsabilidade', models.PositiveSmallIntegerField(choices=[(1, '1 - Muito Abaixo'), (2, '2 - Abaixo do Esperado'), (3, '3 - Esperado'), (4, '4 - Acima do Esperado'), (5, '5 - Excepcional')])),
                ('trabalho_em_equipe', models.PositiveSmallIntegerField(choices=[(1, '1 - Muito Abaixo'), (2, '2 - Abaixo do Esperado'), (3, '3 - Esperado'), (4, '4 - Acima do Esperado'), (5, '5 - Excepcional')], verbose_name='Trabalho em Equipe')),
                ('comunicacao', models.PositiveSmallIntegerField(choices=[(1, '1 - Muito Abaixo'), (2, '2 - Abaixo do Esperado'), (3, '3 - Esperado'), (4, '4 - Acima do Esperado'), (5, '5 - Excepcional')], verbose_name='Comunicação Comportamental')),
                ('resiliencia', models.PositiveSmallIntegerField(choices=[(1, '1 - Muito Abaixo'), (2, '2 - Abaixo do Esperado'), (3, '3 - Esperado'), (4, '4 - Acima do Esperado'), (5, '5 - Excepcional')])),
                ('postura_profissional', models.PositiveSmallIntegerField(choices=[(1, '1 - Muito Abaixo'), (2, '2 - Abaixo do Esperado'), (3, '3 - Esperado'), (4, '4 - Acima do Esperado'), (5, '5 - Excepcional')], verbose_name='Postura Profissional')),
                ('evolucao_individual', models.PositiveSmallIntegerField(choices=[(1, '1 - Muito Abaixo'), (2, '2 - Abaixo do Esperado'), (3, '3 - Esperado'), (4, '4 - Acima do Esperado'), (5, '5 - Excepcional')], verbose_name='Evolução Individual')),
                ('comentario_comportamental', models.TextField(blank=True, null=True, verbose_name='Observações Comportamentais')),
                ('comentario_operacional', models.TextField(blank=True, null=True, verbose_name='Observações Operacionais')),
                ('nota_comportamental', models.FloatField(blank=True, null=True, verbose_name='Média Comportamental')),
                ('nota_operacional', models.FloatField(blank=True, null=True, verbose_name='Média Operacional')),
                ('nota_final', models.FloatField(blank=True, null=True, verbose_name='Nota Final')),
                ('controle_fila_nba5', models.PositiveSmallIntegerField(choices=[(1, '1 - Muito Abaixo'), (2, '2 - Abaixo do Esperado'), (3, '3 - Esperado'), (4, '4 - Acima do Esperado'), (5, '5 - Excepcional')], verbose_name='Controle de Fila / NBA5')),
                ('eficiencia_distribuicao', models.PositiveSmallIntegerField(choices=[(1, '1 - Muito Abaixo'), (2, '2 - Abaixo do Esperado'), (3, '3 - Esperado'), (4, '4 - Acima do Esperado'), (5, '5 - Excepcional')], verbose_name='Eficiência na Distribuição')),
                ('monitoramento_ativo', models.PositiveSmallIntegerField(choices=[(1, '1 - Muito Abaixo'), (2, '2 - Abaixo do Esperado'), (3, '3 - Esperado'), (4, '4 - Acima do Esperado'), (5, '5 - Excepcional')], verbose_name='Monitoramento Ativo da Praça')),
                ('cumprimento_processos', models.PositiveSmallIntegerField(choices=[(1, '1 - Muito Abaixo'), (2, '2 - Abaixo do Esperado'), (3, '3 - Esperado'), (4, '4 - Acima do Esperado'), (5, '5 - Excepcional')], verbose_name='Cumprimento de Processos Padrão')),
                ('resolucao_imprevistos', models.PositiveSmallIntegerField(choices=[(1, '1 - Muito Abaixo'), (2, '2 - Abaixo do Esperado'), (3, '3 - Esperado'), (4, '4 - Acima do Esperado'), (5, '5 - Excepcional')], verbose_name='Resolução de Imprevistos')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacao.colaborador', verbose_name='Colaborador Avaliado')),
                ('hub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='avaliacao.hub', verbose_name='Hub da Avaliação')),
            ],
            options={
                'verbose_name': 'Avaliação de Assistente',
                'verbose_name_plural': 'Avaliações de Assistentes',
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoMensageiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliador', models.CharField(max_length=255)),
                ('data_avaliacao', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Avaliação')),
                ('proatividade', models.PositiveSmallIntegerField(choices=[(1, '1 - Muito Abaixo'), (2, '2 - Abaixo do Esperado'), (3, '3 - Esperado'), (4, '4 - Acima do Esperado'), (5, '5 - Excepcional')])),
                ('responsabilidade', models.PositiveSmallIntegerField(choices=[(1, '1 - Muito Abaixo'), (2, '2 - Abaixo do Esperado'), (3, '3 - Esperado'), (4, '4 - Acima do Esperado'), (5, '5 - Excepcional')])),
                ('trabalho_em_equipe', models.PositiveSmallIntegerField(choices=[(1, '1 - Muito Abaixo'), (2, '2 - Abaixo do Esperado'), (3, '3 - Esperado'), (4, '4 - Acima do Esperado'), (5, '5 - Excepcional')], verbose_name='Trabalho em Equipe')),
                ('comunicacao', models.PositiveSmallIntegerField(choices=[(1, '1 - Muito Abaixo'), (2, '2 - Abaixo do Esperado'), (3, '3 - Esperado'), (4, '4 - Acima do Esperado'), (5, '5 - Excepcional')], verbose_name='Comunicação Comportamental')),
                ('resiliencia', models.PositiveSmallIntegerField(choices=[(1, '1 - Muito Abaixo'), (2, '2 - Abaixo do Esperado'), (3, '3 - Esperado'), (4, '4 - Acima do Esperado'), (5, '5 - Excepcional')])),
                ('postura_profissional', models.PositiveSmallIntegerField(choices=[(1, '1 - Muito Abaixo'), (2, '2 - Abaixo do Esperado'), (3, '3 - Esperado'), (4, '4 - Acima do Esperado'), (5, '5 - Excepcional')], verbose_name='Postura Profissional')),
                ('evolucao_individual', models.PositiveSmallIntegerField(choices=[(1, '1 - Muito Abaixo'), (2, '2 - Abaixo do Esperado'), (3, '3 - Esperado'), (4, '4 - Acima do Esperado'), (5, '5 - Excepcional')], verbose_name='Evolução Individual')),
                ('comentario_comportamental', models.TextField(blank=True, null=True, verbose_name='Observações Comportamentais')),
                ('comentario_operacional', models.TextField(blank=True, null=True, verbose_name='Observações Operacionais')),
                ('nota_comportamental', models.FloatField(blank=True, null=True, verbose_name='Média Comportamental')),
                ('nota_operacional', models.FloatField(blank=True, null=True, verbose_name='Média Operacional')),
                ('nota_final', models.FloatField(blank=True, null=True, verbose_name='Nota Final')),
                ('trm5', models.PositiveSmallIntegerField(choices=[(1, '1 - Muito Abaixo'), (2, '2 - Abaixo do Esperado'), (3, '3 - Esperado'), (4, '4 - Acima do Esperado'), (5, '5 - Excepcional')], verbose_name='TRM5 (Agilidade Carrossel)')),
                ('erros_pedido', models.PositiveSmallIntegerField(choices=[(1, '1 - Muito Abaixo'), (2, '2 - Abaixo do Esperado'), (3, '3 - Esperado'), (4, '4 - Acima do Esperado'), (5, '5 - Excepcional')], verbose_name='Erros de Pedido')),
                ('cumprimento_metas', models.PositiveSmallIntegerField(choices=[(1, '1 - Muito Abaixo'), (2, '2 - Abaixo do Esperado'), (3, '3 - Esperado'), (4, '4 - Acima do Esperado'), (5, '5 - Excepcional')], verbose_name='Cumprimento de Metas Diárias')),
                ('pontualidade', models.PositiveSmallIntegerField(choices=[(1, '1 - Muito Abaixo'), (2, '2 - Abaixo do Esperado'), (3, '3 - Esperado'), (4, '4 - Acima do Esperado'), (5, '5 - Excepcional')])),
                ('organizacao_praca', models.PositiveSmallIntegerField(choices=[(1, '1 - Muito Abaixo'), (2, '2 - Abaixo do Esperado'), (3, '3 - Esperado'), (4, '4 - Acima do Esperado'), (5, '5 - Excepcional')], verbose_name='Organização da Praça')),
                ('comunicacao_central', models.PositiveSmallIntegerField(choices=[(1, '1 - Muito Abaixo'), (2, '2 - Abaixo do Esperado'), (3, '3 - Esperado'), (4, '4 - Acima do Esperado'), (5, '5 - Excepcional')], verbose_name='Comunicação com a Central')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacao.colaborador', verbose_name='Colaborador Avaliado')),
                ('hub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='avaliacao.hub', verbose_name='Hub da Avaliação')),
            ],
            options={
                'verbose_name': 'Avaliação de Mensageiro',
                'verbose_name_plural': 'Avaliações de Mensageiros',
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoRestaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_restaurante', models.CharField(max_length=255, verbose_name='Nome do Restaurante')),
                ('nome_avaliador_restaurante', models.CharField(blank=True, max_length=255, verbose_name='Nome do Avaliador (Restaurante)')),
                ('data_avaliacao', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Avaliação')),
                ('rapidez_atendimento', models.PositiveSmallIntegerField(choices=[(1, '1 - Muito Abaixo'), (2, '2 - Abaixo do Esperado'), (3, '3 - Esperado'), (4, '4 - Acima do Esperado'), (5, '5 - Excepcional')])),
                ('eficiencia_resolucao', models.PositiveSmallIntegerField(choices=[(1, '1 - Muito Abaixo'), (2, '2 - Abaixo do Esperado'), (3, '3 - Esperado'), (4, '4 - Acima do Esperado'), (5, '5 - Excepcional')])),
                ('clareza_comunicacao', models.PositiveSmallIntegerField(choices=[(1, '1 - Muito Abaixo'), (2, '2 - Abaixo do Esperado'), (3, '3 - Esperado'), (4, '4 - Acima do Esperado'), (5, '5 - Excepcional')])),
                ('profissionalismo', models.PositiveSmallIntegerField(choices=[(1, '1 - Muito Abaixo'), (2, '2 - Abaixo do Esperado'), (3, '3 - Esperado'), (4, '4 - Acima do Esperado'), (5, '5 - Excepcional')])),
                ('suporte_gestao_pedidos', models.PositiveSmallIntegerField(choices=[(1, '1 - Muito Abaixo'), (2, '2 - Abaixo do Esperado'), (3, '3 - Esperado'), (4, '4 - Acima do Esperado'), (5, '5 - Excepcional')])),
                ('proatividade', models.PositiveSmallIntegerField(choices=[(1, '1 - Muito Abaixo'), (2, '2 - Abaixo do Esperado'), (3, '3 - Esperado'), (4, '4 - Acima do Esperado'), (5, '5 - Excepcional')])),
                ('disponibilidade', models.PositiveSmallIntegerField(choices=[(1, '1 - Muito Abaixo'), (2, '2 - Abaixo do Esperado'), (3, '3 - Esperado'), (4, '4 - Acima do Esperado'), (5, '5 - Excepcional')])),
                ('satisfacao_geral', models.PositiveSmallIntegerField(choices=[(1, '1 - Muito Abaixo'), (2, '2 - Abaixo do Esperado'), (3, '3 - Esperado'), (4, '4 - Acima do Esperado'), (5, '5 - Excepcional')])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('nota_final', models.FloatField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_recebidas_restaurantes', to='avaliacao.colaborador')),
                ('hub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes_de_restaurantes', to='avaliacao.hub')),
            ],
            options={
                'verbose_name': 'Avaliação do Restaurante',
                'verbose_name_plural': 'Avaliações dos Restaurantes',
                'ordering': ['-data_avaliacao'],
            },
        ),
        migrations.DeleteModel(
            name='Avaliacao',
        ),
        migrations.DeleteModel(
            name='Avaliacao_Restaurante',
        ),
    ]
