# Generated by Django 5.0.2 on 2025-11-15 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0008_remove_avaliacao_restaurante_colaborador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='cargo',
            field=models.CharField(choices=[('Líder de Logística', 'Líder de Logística'), ('Assistente de Logística', 'Assistente de Logística'), ('Mensageiro', 'Mensageiro'), ('Supervisor', 'Supervisor'), ('Staff', 'Staff')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='SugestaoMedalha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('1_ano', '1 Ano de Hub'), ('2_anos', '2 Anos de Hub'), ('3_anos', '3 Anos de Hub'), ('logistica', 'Logística Implacável'), ('mensageiro', '1# Mensageiro'), ('pontual', 'Super Pontual'), ('criatividade', 'Criatividade'), ('destaque', 'Colaborador Destaque'), ('comunicação', 'Comunicação Eficiente'), ('carisma', 'Carisma'), ('dedicação', 'Dedicação'), ('analista', 'Analista de Dados')], max_length=50)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceita', 'Aceita'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=20)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacao.colaborador')),
            ],
        ),
    ]
