# Generated by Django 5.0.2 on 2025-11-15 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0009_alter_colaborador_cargo_sugestaomedalha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sugestaomedalha',
            name='status',
        ),
    ]
